version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always
```

###  Créer le fichier .dockerignore**

Crée `.dockerignore` :
```
node_modules
.env
.git
*.md